plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - index.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
exclude:
  - README.md
#   - TODO.md
remote_theme: pmarsceill/just-the-docs@v0.3.3
plugins:
- jekyll-remote-theme 

color_scheme: dark-mod
aux_links:
  "Send a pull request":
    - "//github.com/zhol0777/is-this-good"

